import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  fr: {
    // Navbar
    dashboard: 'Tableau de bord',
    products: 'Produits',
    batches: 'Lots / Séries',
    locations: 'Emplacements',
    replenishment: 'Réappro',
    orders: 'Commandes',
    restocking: 'Remplissage',
    picking: 'Collecte',
    scanner: 'Scanner',
    movements: 'Mouvements',
    alerts: 'Alertes',
    configuration: 'Configuration',
    suppliers: 'Fournisseurs',
    productTypes: 'Types de produit',
    administration: 'Administration',
    employees: 'Employés',
    logout: 'Déconnexion',
    appSubtitle: 'Gestion des dispositifs médicaux implantables',
    
    // Common actions
    add: 'Ajouter',
    edit: 'Modifier',
    delete: 'Supprimer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    search: 'Rechercher',
    filter: 'Filtrer',
    export: 'Exporter',
    create: 'Créer',
    update: 'Mettre à jour',
    close: 'Fermer',
    reset: 'Réinitialiser',
    
    // Read-only messages
    readOnlyMode: 'Mode lecture seule',
    readOnlyProducts: 'Les modifications sont désactivées',
    readOnlyPicking: 'La collecte est désactivée',
    readOnlyRestocking: 'Le remplissage est désactivé',
    readOnlyReplenishment: 'Le réapprovisionnement est désactivé',
    readOnlyMovements: "L'enregistrement de mouvements est désactivé",
    readOnlyLocations: "L'ajout d'emplacements est désactivé",
    readOnlySuppliers: "L'ajout de fournisseurs est désactivé",
    readOnlyProductTypes: "L'ajout de types de produit est désactivé",
    accessRestricted: 'Accès restreint',
    roleNotAllowed: "Votre rôle ne permet pas d'effectuer cette action",
    
    // Dashboard
    totalProducts: 'Produits totaux',
    criticalStock: 'Stock critique',
    expiringProducts: 'Expirations proches',
    recentMovements: 'Mouvements récents',
    
    // Products page
    productCatalog: 'Catalogue de produits',
    manageProducts: 'Gérez votre catalogue de produits médicaux',
    addProduct: 'Ajouter un produit',
    editProduct: 'Modifier le produit',
    newProduct: 'Nouveau produit',
    productName: 'Nom du produit',
    reference: 'Référence',
    type: 'Type',
    manufacturer: 'Fabricant',
    minStock: 'Stock minimum',
    maxStock: 'Stock maximum',
    
    // Batches page
    batchManagement: 'Gestion des numéros de Lots / Séries',
    groupedView: 'Vue groupée par produit et numéro de lot/série',
    lotNumber: 'Numéro de lot',
    serialNumber: 'Numéro de série',
    expirationDate: 'Date d\'expiration',
    manufacturingDate: 'Date de fabrication',
    quantity: 'Quantité',
    location: 'Emplacement',
    catalogNumber: 'N° Catalogue',
    name: 'Nom',
    groupsUnits: 'groupe(s) - unité(s) en stock',
    product: 'Produit',
    status: 'Statut',
    available: 'Disponible',
    used: 'Utilisé',
    reserved: 'Réservé',
    expired: 'Expiré',
    expiringSoon: 'Expire bientôt',
    valid: 'Valide',
    
    // Picking page
    pickingTitle: 'Collecte',
    pickingDescription: 'Collectez les produits selon le principe FIFO (expiration la plus proche)',
    scanProduct: 'Scanner un produit',
    scanOrEnter: 'Scannez ou saisissez le numéro de série ou de lot',
    manualSelection: 'Sélection manuelle',
    selectProduct: 'Sélectionner un produit',
    availableLots: 'Lots disponibles',
    selectedLots: 'lot(s) sélectionné(s)',
    requestPicking: 'Demander la collecte',
    pickSelectedLots: 'Collecter les lots sélectionnés',
    fifoAutomatic: 'FIFO auto',
    patientValidation: 'Validation du dossier patient',
    patientNumber: 'Numéro de dossier patient',
    confirmPicking: 'Confirmer la collecte',
    cancelPicking: 'Annuler',
    newPicking: 'Nouvelle collecte',
    
    // Expired product approval
    expiredProduct: 'PRODUIT EXPIRÉ',
    managerApprovalRequired: "Ce produit nécessite l'approbation d'un gestionnaire",
    expiredProductsApproval: 'Produit(s) expiré(s) - Approbation requise',
    expiredProductsInList: 'produit(s) expiré(s) dans cette liste',
    expiredPickingWarning: "La collecte de produits expirés nécessite l'approbation d'un gestionnaire",
    managerCode: 'Code gestionnaire',
    enterManagerPin: 'Entrez le code PIN du gestionnaire',
    pinTraceability: 'Le code PIN est lié à votre compte gestionnaire et sera enregistré pour traçabilité',
    approvePicking: 'Approuver la collecte',
    invalidManagerCode: 'Code gestionnaire invalide',
    pickingApprovedBy: 'Collecte approuvée par',
    
    // Surgical Request Picking (Sélection par requête)
    selectionByRequest: 'Sélection par requête',
    selectSurgicalRequest: 'Sélectionnez une requête chirurgicale pour voir les produits requis',
    noSurgicalRequests: 'Aucune requête chirurgicale pour le moment',
    dateTime: 'Date & Heure',
    requestNumber: 'N° Requête',
    specialty: 'Spécialité',
    intervention: 'Intervention',
    surgeon: 'Chirurgien',
    operatingRoom: 'Salle',
    action: 'Action',
    select: 'Sélectionner',
    requiredProducts: 'Produits requis',
    clickToSelect: 'Cliquez sur les produits à collecter',
    requestPicking: 'Demander la collecte',
    pickingConfirmation: 'Confirmation de la collecte',
    patientNumberRequired: 'N° Patient *',
    enterPatientNumber: 'Entrez le numéro de dossier patient',
    selectedArticles: 'Articles sélectionnés',
    back: 'Retour',
    confirmPickingBtn: 'Confirmer la collecte',
    cancel: 'Annuler',
    valid: 'valide',
    expired: 'expiré',
    expiringSoon: 'expiration proche',
    daysRemaining: 'j',
    
    // Locations page
    locationsTitle: 'Emplacements',
    locationsDescription: 'Gestion des positions dans les armoires',
    addLocation: 'Ajouter un emplacement',
    newLocation: 'Nouvel emplacement',
    cabinet: 'Armoire',
    row: 'Rangée',
    column: 'Colonne',
    generatedCode: 'Code généré',
    createLocation: "Créer l'emplacement",
    occupied: 'Occupé',
    free: 'Libre',
    code: 'Code',
    status: 'Statut',
    available: 'Disponible',
    lotNumber: 'N° Lot',
    serialNumber: 'N° Série',
    grmNumber: 'N° GRM',
    sortBy: 'Trier par',
    productType: 'Type de produit',
    selectProductType: 'Sélectionner un type',
    productTypeHelp: 'Seuls les produits de ce type pourront être placés ici',
    all: 'Tous',
    allCabinets: 'Toutes',
    totalLocations: 'Total emplacements',
    availableLocations: 'Disponibles',
    occupiedLocations: 'Occupés',
    searchLocations: 'Recherche (code, produit, réf, GRM, lot, série)',
    
    // Movements page
    movementsTitle: 'Mouvements',
    movementsDescription: 'Historique des entrées et sorties de stock',
    recordMovement: 'Enregistrer un mouvement',
    newMovement: 'Nouveau mouvement',
    movementType: 'Type de mouvement',
    entry: 'Entrée',
    exit: 'Sortie',
    replenishmentType: 'Réappro',
    reception: 'Réception',
    batch: 'Lot',
    reason: 'Raison',
    qty: 'Qté',
    entryUpper: 'ENTRÉE',
    exitUpper: 'SORTIE',
    quantityUpper: 'QUANTITÉ',
    filterByType: 'Filtrer par type',
    allTypes: 'Tous les types',
    dateFrom: 'Date début',
    dateTo: 'Date fin',
    exportExcel: 'Exporter Excel',
    movementsFound: 'mouvement(s) trouvé(s)',
    reasonUpper: 'RAISON',
    
    // Replenishment page
    replenishmentTitle: 'Réappro',
    replenishmentDescription: 'Gérez les commandes de réapprovisionnement',
    generatePdf: 'Générer PDF',
    exportExcel: 'Exporter Excel',
    selectAll: 'Tout sélectionner',
    deselectAll: 'Tout désélectionner',
    productsToReplenish: 'produits à réapprovisionner',
    stockBelowMin: 'Stock inférieur au minimum requis',
    generatePdfMark: 'Générer PDF & Marquer',
    exportExcelUpper: 'EXPORTER EXCEL',
    exportPdf: 'Exporter PDF',
    markAsOrdered: 'Commander',
    ordered: 'Commandé',
    toOrder: 'À commander',
    stock: 'Stock',
    min: 'Min',
    max: 'Max',
    
    // Orders page
    ordersTitle: 'Commandes',
    ordersDescription: 'Gestion des commandes fournisseurs et réception',
    newOrder: 'Ajout consigne',
    orderNumber: 'Numéro de PO',
    supplier: 'Fournisseur',
    selectSupplier: 'Sélectionner un fournisseur',
    expectedDelivery: 'Livraison prévue',
    viewReceive: 'Voir / Recevoir',
    productsOrdered: 'produit(s) commandé(s)',
    partialReceived: 'Reçu partiel',
    fullReceived: 'Reçu complet',
    pending: 'En attente',
    receiving: 'Réception',
    placement: 'Placement',
    selectProductToReceive: 'Sélectionner un produit à recevoir',
    received: 'Reçu',
    remaining: 'Restant',
    quantityToReceive: 'Quantité à recevoir',
    previousBatches: 'Historique (même produit)',
    usePrevious: 'Utiliser',
    batchInfo: 'Informations du produit reçu',
    manufacturingDate: 'Date de fabrication',
    barcode: 'Code-barres',
    barcodeForUnit: 'Codes-barres individuels',
    receiveProducts: 'Recevoir les produits',
    suggestedLocation: 'Emplacement suggéré',
    scanLocationQR: 'Scanner le QR code de l\'emplacement',
    confirmPlacement: 'Confirmer l\'emplacement',
    cancelReceiving: 'Annuler la réception',
    newLot: 'Nouveau lot',
    newSerial: 'Nouveau n° série',
    serialSuffix: 'Les n° de série seront suffixés: -1, -2, etc.',
    optional: 'optionnel',
    unit: 'Unité',
    units: 'unités',
    
    // Restocking page
    restockingTitle: 'Remplissage',
    restockingDescription: 'Retour dans les armoires des produits non utilisés',
    scanProductStep: '1. Scanner le produit',
    confirmLocationStep: "2. Confirmer l'emplacement",
    identifyProduct: 'Identifier le produit collecté',
    noProductsToRestock: 'Aucun produit à remettre en stock',
    allProductsUsed: 'Tous les produits collectés ont été utilisés ou remis en stock.',
    scanBarcode: 'Scanner le code-barres du produit',
    confirmRestocking: 'Confirmer le remplissage',
    scanBarcodeAuto: 'Scannez le code-barres pour remplir automatiquement les informations',
    orSelectFromList: 'Ou sélectionner dans la liste des produits collectés',
    requestLocation: 'Demander un emplacement',
    scan: 'Scanner',
    scanOrSearchBarcode: 'Scannez ou recherchez un code-barres/QR code',
    scanProductTitle: 'Scanner un produit',
    scanBarcodeHelp: 'Scannez le code-barres ou saisissez : Code-barres, Numéro de série, Numéro de lot ou Référence produit',
    confirmLocation: 'Confirmer l\'emplacement',
    step2ConfirmRestocking: 'Étape 2: Confirmation du remplissage',
    placeProductAt: 'Placez le produit à l\'emplacement',
    thenScanQR: 'puis scannez le QR code de l\'emplacement pour confirmer.',
    locationQRCode: 'QR Code de l\'emplacement',
    expected: 'Attendu',
    selectedProduct: 'Produit sélectionné',
    scanBarcodeOrRfid: 'Scanner Code-barres',
    scanBarcodeOrRfidPlaceholder: 'Scannez le code-barres',
    scanUniversalHelp: 'Le scan recherche automatiquement par code-barres, numéro de série ou numéro de lot',
    
    // Suppliers page
    suppliersTitle: 'Fournisseurs',
    suppliersDescription: 'Gérer les fournisseurs disponibles pour les produits',
    addSupplier: 'Ajouter un fournisseur',
    newSupplier: 'Nouveau fournisseur',
    supplierName: 'Nom du fournisseur',
    
    // Product types page
    productTypesTitle: 'Types de produit',
    productTypesDescription: 'Gérer les types disponibles pour les produits',
    addType: 'Ajouter un type',
    newType: 'Nouveau type de produit',
    typeName: 'Nom du type',
    
    // Employees page
    employeesTitle: 'Gestion des Employés',
    employeesDescription: 'Gérez les utilisateurs et leurs permissions',
    newEmployee: 'Nouvel employé',
    editEmployee: "Modifier l'employé",
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Email',
    password: 'Mot de passe',
    role: 'Rôle',
    pin: 'Code PIN',
    pinForApproval: 'pour approbation des produits expirés',
    employeeCardId: 'ID Carte',
    employeeCardIdPlaceholder: 'ID unique de la carte employé',
    cardLogin: 'Connexion par carte',
    configured: 'Configuré',
    notConfigured: 'Non configuré',
    creationDate: 'Date création',
    actions: 'Actions',
    totalEmployees: 'Total employés',
    administrators: 'Administrateurs',
    withPin: 'Avec PIN',
    managers: 'Gestionnaires',
    fullName: 'NOM COMPLET',
    roleUpper: 'RÔLE',
    
    // Roles
    roleAdministrator: 'Administrateur',
    roleManager: 'Gestionnaire',
    roleTechnician: 'Technicien',
    roleSurgeon: 'Chirurgien',
    roleReadOnly: 'Lecture seule',
    roleAdminDesc: 'Accès complet à toutes les fonctionnalités',
    roleManagerDesc: 'Gestion des stocks, approbation des produits expirés',
    roleTechnicianDesc: 'Opérations de stock (réception, collecte, remplissage)',
    roleSurgeonDesc: 'Collecte de produits uniquement',
    roleReadOnlyDesc: 'Consultation des données uniquement',
    
    // Alerts page
    alertsTitle: 'Alertes',
    alertsDescription: 'Gestion des alertes de stock et d\'expiration',
    noAlerts: 'Aucune alerte active',
    allStocksOk: 'Tous vos stocks sont en bon état',
    stockAlerts: 'Alertes de stock',
    
    // Common
    noData: 'Aucune donnée',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    warning: 'Attention',
    stockAvailable: 'Stock disponible',
    unit: 'unité',
    units: 'unités',
    scannerTitle: 'Scanner',
    scanOrEnterCode: 'Scanner ou saisir le code...',
    batchIdentified: 'Lot identifié',
    newScan: 'Nouveau scan',
    productInfo: 'Informations du produit',
    availableStock: 'Stock disponible',
    active: 'Actif',
  },
  
  en: {
    // Navbar
    dashboard: 'Dashboard',
    products: 'Products',
    batches: 'Lots / Serials',
    locations: 'Locations',
    replenishment: 'Replenishment',
    orders: 'Orders',
    restocking: 'Restocking',
    picking: 'Picking',
    scanner: 'Scanner',
    movements: 'Movements',
    alerts: 'Alerts',
    configuration: 'Configuration',
    suppliers: 'Suppliers',
    productTypes: 'Product Types',
    administration: 'Administration',
    employees: 'Employees',
    logout: 'Logout',
    appSubtitle: 'Implantable Medical Device Management',
    
    // Common actions
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    create: 'Create',
    update: 'Update',
    close: 'Close',
    reset: 'Reset',
    
    // Read-only messages
    readOnlyMode: 'Read-only mode',
    readOnlyProducts: 'Modifications are disabled',
    readOnlyPicking: 'Picking is disabled',
    readOnlyRestocking: 'Restocking is disabled',
    readOnlyReplenishment: 'Replenishment is disabled',
    readOnlyMovements: 'Recording movements is disabled',
    readOnlyLocations: 'Adding locations is disabled',
    readOnlySuppliers: 'Adding suppliers is disabled',
    readOnlyProductTypes: 'Adding product types is disabled',
    accessRestricted: 'Access Restricted',
    roleNotAllowed: 'Your role does not allow this action',
    
    // Dashboard
    totalProducts: 'Total Products',
    criticalStock: 'Critical Stock',
    expiringProducts: 'Expiring Soon',
    recentMovements: 'Recent Movements',
    
    // Products page
    productCatalog: 'Product Catalog',
    manageProducts: 'Manage your medical product catalog',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    newProduct: 'New Product',
    productName: 'Product Name',
    reference: 'Reference',
    type: 'Type',
    manufacturer: 'Manufacturer',
    minStock: 'Min Stock',
    maxStock: 'Max Stock',
    
    // Batches page
    batchManagement: 'Lot / Serial Number Management',
    groupedView: 'Grouped view by product and lot/serial number',
    lotNumber: 'Lot Number',
    serialNumber: 'Serial Number',
    expirationDate: 'Expiration Date',
    manufacturingDate: 'Manufacturing Date',
    quantity: 'Quantity',
    location: 'Location',
    status: 'Status',
    available: 'Available',
    used: 'Used',
    reserved: 'Reserved',
    expired: 'Expired',
    expiringSoon: 'Expiring Soon',
    valid: 'Valid',
    catalogNumber: 'Catalog No.',
    name: 'Name',
    groupsUnits: 'group(s) - unit(s) in stock',
    product: 'Product',
    
    // Picking page
    pickingTitle: 'Picking',
    pickingDescription: 'Pick products following FIFO principle (closest expiration first)',
    scanProduct: 'Scan a product',
    scanOrEnter: 'Scan or enter the serial or lot number',
    manualSelection: 'Manual Selection',
    selectProduct: 'Select a product',
    availableLots: 'Available lots',
    selectedLots: 'lot(s) selected',
    requestPicking: 'Request Picking',
    pickSelectedLots: 'Pick selected lots',
    fifoAutomatic: 'Auto FIFO',
    patientValidation: 'Patient File Validation',
    patientNumber: 'Patient file number',
    confirmPicking: 'Confirm Picking',
    cancelPicking: 'Cancel',
    newPicking: 'New Picking',
    
    // Expired product approval
    expiredProduct: 'EXPIRED PRODUCT',
    managerApprovalRequired: 'This product requires manager approval',
    expiredProductsApproval: 'Expired product(s) - Approval required',
    expiredProductsInList: 'expired product(s) in this list',
    expiredPickingWarning: 'Picking expired products requires manager approval',
    managerCode: 'Manager Code',
    enterManagerPin: 'Enter manager PIN code',
    pinTraceability: 'The PIN code is linked to your manager account and will be recorded for traceability',
    approvePicking: 'Approve Picking',
    invalidManagerCode: 'Invalid manager code',
    pickingApprovedBy: 'Picking approved by',
    
    // Surgical Request Picking (Selection by request)
    selectionByRequest: 'Selection by Request',
    selectSurgicalRequest: 'Select a surgical request to view required products',
    noSurgicalRequests: 'No surgical requests at the moment',
    dateTime: 'Date & Time',
    requestNumber: 'Request #',
    specialty: 'Specialty',
    intervention: 'Intervention',
    surgeon: 'Surgeon',
    operatingRoom: 'Room',
    action: 'Action',
    select: 'Select',
    requiredProducts: 'Required Products',
    clickToSelect: 'Click on products to pick',
    requestPicking: 'Request Picking',
    pickingConfirmation: 'Picking Confirmation',
    patientNumberRequired: 'Patient # *',
    enterPatientNumber: 'Enter patient file number',
    selectedArticles: 'Selected Articles',
    back: 'Back',
    confirmPickingBtn: 'Confirm Picking',
    cancel: 'Cancel',
    valid: 'valid',
    expired: 'expired',
    expiringSoon: 'expiring soon',
    daysRemaining: 'd',
    
    // Locations page
    locationsTitle: 'Locations',
    locationsDescription: 'Manage cabinet positions',
    addLocation: 'Add Location',
    newLocation: 'New Location',
    cabinet: 'Cabinet',
    row: 'Row',
    column: 'Column',
    generatedCode: 'Generated Code',
    createLocation: 'Create Location',
    occupied: 'Occupied',
    free: 'Free',
    code: 'Code',
    grmNumber: 'GRM Number',
    sortBy: 'Sort by',
    all: 'All',
    allCabinets: 'All',
    totalLocations: 'Total locations',
    availableLocations: 'Available',
    occupiedLocations: 'Occupied',
    searchLocations: 'Search (code, product, ref, GRM, lot, serial)',
    productType: 'Product Type',
    selectProductType: 'Select a type',
    productTypeHelp: 'Only products of this type can be placed here',
    
    // Movements page
    movementsTitle: 'Movements',
    movementsDescription: 'Stock entry and exit history',
    recordMovement: 'Record Movement',
    newMovement: 'New Movement',
    movementType: 'Movement Type',
    entry: 'Entry',
    exit: 'Exit',
    replenishmentType: 'Replenishment',
    reception: 'Reception',
    batch: 'Batch',
    reason: 'Reason',
    qty: 'Qty',
    entryUpper: 'ENTRY',
    exitUpper: 'EXIT',
    quantityUpper: 'QUANTITY',
    reasonUpper: 'REASON',
    filterByType: 'Filter by type',
    allTypes: 'All types',
    dateFrom: 'Start date',
    dateTo: 'End date',
    exportExcel: 'Export Excel',
    movementsFound: 'movement(s) found',
    
    // Replenishment page
    replenishmentTitle: 'Replenishment',
    replenishmentDescription: 'Manage replenishment orders',
    generatePdf: 'Generate PDF',
    exportExcel: 'Export Excel',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    productsToReplenish: 'products to replenish',
    stockBelowMin: 'Stock below minimum required',
    generatePdfMark: 'Generate PDF & Mark',
    exportExcelUpper: 'EXPORT EXCEL',
    exportPdf: 'Export PDF',
    markAsOrdered: 'Order',
    ordered: 'Ordered',
    toOrder: 'To order',
    stock: 'Stock',
    min: 'Min',
    max: 'Max',
    
    // Orders page
    ordersTitle: 'Orders',
    ordersDescription: 'Supplier orders and receiving management',
    newOrder: 'Add Consignment',
    orderNumber: 'PO Number',
    supplier: 'Supplier',
    selectSupplier: 'Select a supplier',
    expectedDelivery: 'Expected Delivery',
    viewReceive: 'View / Receive',
    productsOrdered: 'product(s) ordered',
    partialReceived: 'Partial Received',
    fullReceived: 'Full Received',
    pending: 'Pending',
    receiving: 'Receiving',
    placement: 'Placement',
    selectProductToReceive: 'Select a product to receive',
    received: 'Received',
    remaining: 'Remaining',
    quantityToReceive: 'Quantity to receive',
    previousBatches: 'History (same product)',
    usePrevious: 'Use',
    batchInfo: 'Received product information',
    manufacturingDate: 'Manufacturing date',
    barcode: 'Barcode',
    barcodeForUnit: 'Individual barcodes',
    receiveProducts: 'Receive products',
    suggestedLocation: 'Suggested location',
    scanLocationQR: 'Scan location QR code',
    confirmPlacement: 'Confirm placement',
    cancelReceiving: 'Cancel receiving',
    newLot: 'New lot',
    newSerial: 'New serial no.',
    serialSuffix: 'Serial numbers will be suffixed: -1, -2, etc.',
    optional: 'optional',
    unit: 'Unit',
    units: 'units',
    
    // Restocking page
    restockingTitle: 'Restocking',
    restockingDescription: 'Return unused products to cabinets',
    scanProductStep: '1. Scan product',
    confirmLocationStep: '2. Confirm location',
    identifyProduct: 'Identify picked product',
    noProductsToRestock: 'No products to restock',
    allProductsUsed: 'All picked products have been used or restocked.',
    scanBarcode: 'Scan product barcode',
    confirmRestocking: 'Confirm Restocking',
    scanBarcodeAuto: 'Scan the barcode to automatically fill in the information',
    orSelectFromList: 'Or select from the list of picked products',
    requestLocation: 'Request location',
    scan: 'Scan',
    scanOrSearchBarcode: 'Scan or search for a barcode/QR code',
    scanProductTitle: 'Scan a product',
    scanBarcodeHelp: 'Scan the barcode or enter: Barcode, Serial number, Lot number or Product reference',
    confirmLocation: 'Confirm location',
    step2ConfirmRestocking: 'Step 2: Confirm restocking',
    placeProductAt: 'Place the product at location',
    thenScanQR: 'then scan the location QR code to confirm.',
    locationQRCode: 'Location QR Code',
    expected: 'Expected',
    selectedProduct: 'Selected product',
    scanBarcodeOrRfid: 'Scan Barcode',
    scanBarcodeOrRfidPlaceholder: 'Scan the barcode',
    scanUniversalHelp: 'The scan searches automatically by barcode, serial number or lot number',
    
    // Suppliers page
    suppliersTitle: 'Suppliers',
    suppliersDescription: 'Manage available suppliers for products',
    addSupplier: 'Add Supplier',
    newSupplier: 'New Supplier',
    supplierName: 'Supplier Name',
    
    // Product types page
    productTypesTitle: 'Product Types',
    productTypesDescription: 'Manage available product types',
    addType: 'Add Type',
    newType: 'New Product Type',
    typeName: 'Type Name',
    
    // Employees page
    employeesTitle: 'Employee Management',
    employeesDescription: 'Manage users and their permissions',
    newEmployee: 'New Employee',
    editEmployee: 'Edit Employee',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    password: 'Password',
    role: 'Role',
    pin: 'PIN Code',
    pinForApproval: 'for expired product approval',
    employeeCardId: 'Card ID',
    employeeCardIdPlaceholder: 'Unique employee card ID',
    cardLogin: 'Card login',
    configured: 'Configured',
    notConfigured: 'Not configured',
    creationDate: 'Creation Date',
    actions: 'Actions',
    totalEmployees: 'Total Employees',
    administrators: 'Administrators',
    withPin: 'With PIN',
    managers: 'Managers',
    fullName: 'FULL NAME',
    roleUpper: 'ROLE',
    
    // Roles
    roleAdministrator: 'Administrator',
    roleManager: 'Manager',
    roleTechnician: 'Technician',
    roleSurgeon: 'Surgeon',
    roleReadOnly: 'Read Only',
    roleAdminDesc: 'Full access to all features',
    roleManagerDesc: 'Stock management, expired product approval',
    roleTechnicianDesc: 'Stock operations (receiving, picking, restocking)',
    roleSurgeonDesc: 'Product picking only',
    roleReadOnlyDesc: 'View data only',
    
    // Alerts page
    alertsTitle: 'Alerts',
    alertsDescription: 'Stock and expiration alert management',
    noAlerts: 'No active alerts',
    allStocksOk: 'All your stocks are in good condition',
    stockAlerts: 'Stock Alerts',
    
    // Common
    noData: 'No data',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    stockAvailable: 'Stock available',
    unit: 'unit',
    units: 'units',
    scannerTitle: 'Scanner',
    scanOrEnterCode: 'Scan or enter code...',
    batchIdentified: 'Batch identified',
    newScan: 'New scan',
    productInfo: 'Product information',
    availableStock: 'Available stock',
    active: 'Active',
  }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('chrono_dmi_language');
    return saved || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('chrono_dmi_language', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'fr' ? 'en' : 'fr');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
